// Generated by Wrangler on Fri Jun 28 2024 20:55:22 GMT-0400 (Eastern Daylight Saving Time)
// by running `wrangler types`

interface Env {
	go_service_alerts: KVNamespace;
	THREADS_ACCESS_TOKEN: string;
	THREADS_USER_ID: string;
}
